DROP TABLE IF EXISTS supporters CASCADE;
DROP TABLE IF EXISTS sender_emails CASCADE;
DROP TABLE IF EXISTS policy CASCADE;
DROP TABLE IF EXISTS email_logs CASCADE;
DROP VIEW IF EXISTS daily_messages_analytics CASCADE;
